import { expect, test } from '@playwright/test'

test('applies a link to the selected text while other Markdown in the line is pending', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '写作', exact: true }).click()
  await page.getByRole('tab', { name: '排版' }).click()
  const editor = page.getByRole('textbox', { name: 'Markdown 编辑器' })
  await editor.click()
  await editor.pressSequentially('**粗体** 链接 尾部')
  await editor.evaluate((element) => {
    const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT)
    while (walker.nextNode()) {
      const node = walker.currentNode
      const start = node.textContent?.indexOf('链接') ?? -1
      if (start < 0) continue
      const range = document.createRange()
      range.setStart(node, start)
      range.setEnd(node, start + 2)
      window.getSelection()?.removeAllRanges()
      window.getSelection()?.addRange(range)
      document.dispatchEvent(new Event('selectionchange'))
      return
    }
    throw new Error('Link text is missing')
  })
  await page.getByRole('button', { name: '链接', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '插入链接' })
  await expect(dialog.getByLabel('链接文字')).toHaveValue('链接')
  await dialog.getByLabel('链接地址').fill('https://example.com')
  await dialog.getByRole('button', { name: '插入链接' }).click()
  await expect(editor.locator('a')).toHaveText('链接')
  await page.getByLabel('标题', { exact: true }).click()
  await expect(editor.locator('strong')).toHaveText('粗体')
  await expect(editor).toContainText('尾部')
})

test('defers typed Markdown until leaving the paragraph and keeps toolbar formatting immediate', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '写作', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Markdown 编辑器' })
  await editor.click()
  for (const level of [1, 2, 3, 4, 5, 6]) {
    await editor.pressSequentially(`${'#'.repeat(level)} 标题${level}`)
    await expect(editor.locator(`h${level}`)).toHaveCount(0)
    await expect(editor.locator('.editor-markdown-marker')).toContainText('#'.repeat(level))
    await editor.press('Enter')
    await expect(editor.locator(`h${level}`)).toHaveText(`标题${level}`)
  }
  await editor.pressSequentially('**中文加粗** *中文斜体* ~~删除文字~~')
  await expect(editor.locator('strong, em, s')).toHaveCount(0)
  await editor.press('Enter')
  await expect(editor.locator('strong')).toHaveText('中文加粗')
  await expect(editor.locator('em')).toHaveText('中文斜体')
  await expect(editor.locator('s')).toHaveText('删除文字')
  await editor.pressSequentially('下一行普通文字')
  await expect(editor.locator('strong')).not.toContainText('下一行普通文字')
  await page.getByRole('tab', { name: '排版' }).click()
  await page.getByRole('button', { name: '加粗' }).click()
  await editor.pressSequentially('工具栏加粗')
  await expect(page.getByRole('button', { name: '加粗' })).toHaveAttribute('aria-pressed', 'true')
  await editor.press('Enter')
  await expect(page.getByRole('button', { name: '加粗' })).toHaveAttribute('aria-pressed', 'false')
  await editor.pressSequentially('工具栏后的普通文字')
  const plainAfterToolbar = editor.locator('p').filter({ hasText: '工具栏后的普通文字' })
  await expect(plainAfterToolbar).toHaveCount(1)
  await expect(plainAfterToolbar.locator('strong, em, s')).toHaveCount(0)
  await page.getByRole('button', { name: '二级标题' }).click()
  await expect(editor.locator('h2')).toHaveCount(2)
  await page.getByRole('button', { name: '源代码', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Markdown 编辑器' })).toContainText('~~删除文字~~')
  await expect(page.getByRole('textbox', { name: 'Markdown 编辑器' })).not.toContainText('\\*')
})

test('commits inline Markdown after inherited formatting and editor blur without writing hints', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '写作', exact: true }).click()
  const editor = page.getByRole('textbox', { name: 'Markdown 编辑器' })
  await editor.click()
  await editor.pressSequentially('**已有加粗**')
  await editor.press('Enter')
  const bold = editor.locator('strong')
  const bounds = await bold.boundingBox()
  if (!bounds) throw new Error('Bold text is not visible')
  await bold.click({ position: { x: bounds.width - 1, y: bounds.height / 2 } })
  await editor.pressSequentially(' *继续斜体* ~~删除~~')
  await expect(editor.locator('em, s')).toHaveCount(0)
  await page.getByLabel('标题', { exact: true }).click()
  await expect(editor.locator('em')).toHaveText('继续斜体')
  await expect(editor.locator('s')).toHaveText('删除')
  await expect(editor.locator('strong').first()).toContainText('已有加粗')
  await expect(page.locator('.editor-context-hint')).toHaveCount(0)
  await expect(page.locator('.editor-save-status')).toBeVisible()
})
